name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      # --- NEW STEP TO FIX PERMISSION DENIED ---
      - name: Fix permissions
        run: chmod +x node_modules/.bin/vite

      # --- This step will now work ---
      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # This step is still needed
      - name: Install AWS CLI
        run: |
          pip3 install awscli

      - name: Deploy to S3
        run: |
          # We deploy the 'dist' folder, which is Vite's default build output
          aws s3 sync ./dist s3://mindvault-project --delete
